{{- if .Values.observer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gastown-operator.fullname" . }}-observer
  labels:
    {{- include "gastown-operator.labels" . | nindent 4 }}
    app: dgt-observer
spec:
  type: ClusterIP
  selector:
    app: dgt-observer
  ports:
  - name: metrics
    port: 9091
    targetPort: metrics
    protocol: TCP
{{- end }}
