//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRole) DeepCopyInto(out *AgentRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRole.
func (in *AgentRole) DeepCopy() *AgentRole {
	if in == nil {
		return nil
	}
	out := new(AgentRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleIdentity) DeepCopyInto(out *AgentRoleIdentity) {
	*out = *in
	out.ClaudeMdRef = in.ClaudeMdRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleIdentity.
func (in *AgentRoleIdentity) DeepCopy() *AgentRoleIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentRoleIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleList) DeepCopyInto(out *AgentRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleList.
func (in *AgentRoleList) DeepCopy() *AgentRoleList {
	if in == nil {
		return nil
	}
	out := new(AgentRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleResources) DeepCopyInto(out *AgentRoleResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleResources.
func (in *AgentRoleResources) DeepCopy() *AgentRoleResources {
	if in == nil {
		return nil
	}
	out := new(AgentRoleResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleSpec) DeepCopyInto(out *AgentRoleSpec) {
	*out = *in
	out.Identity = in.Identity
	out.Trigger = in.Trigger
	out.Supervision = in.Supervision
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleSpec.
func (in *AgentRoleSpec) DeepCopy() *AgentRoleSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleStatus) DeepCopyInto(out *AgentRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSeenAt != nil {
		in, out := &in.LastSeenAt, &out.LastSeenAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleStatus.
func (in *AgentRoleStatus) DeepCopy() *AgentRoleStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleSupervision) DeepCopyInto(out *AgentRoleSupervision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleSupervision.
func (in *AgentRoleSupervision) DeepCopy() *AgentRoleSupervision {
	if in == nil {
		return nil
	}
	out := new(AgentRoleSupervision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRoleTrigger) DeepCopyInto(out *AgentRoleTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRoleTrigger.
func (in *AgentRoleTrigger) DeepCopy() *AgentRoleTrigger {
	if in == nil {
		return nil
	}
	out := new(AgentRoleTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltInstance) DeepCopyInto(out *DoltInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltInstance.
func (in *DoltInstance) DeepCopy() *DoltInstance {
	if in == nil {
		return nil
	}
	out := new(DoltInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DoltInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltInstanceList) DeepCopyInto(out *DoltInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DoltInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltInstanceList.
func (in *DoltInstanceList) DeepCopy() *DoltInstanceList {
	if in == nil {
		return nil
	}
	out := new(DoltInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DoltInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltInstanceSpec) DeepCopyInto(out *DoltInstanceSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	out.Service = in.Service
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltInstanceSpec.
func (in *DoltInstanceSpec) DeepCopy() *DoltInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DoltInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltInstanceStatus) DeepCopyInto(out *DoltInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltInstanceStatus.
func (in *DoltInstanceStatus) DeepCopy() *DoltInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DoltInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltService) DeepCopyInto(out *DoltService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltService.
func (in *DoltService) DeepCopy() *DoltService {
	if in == nil {
		return nil
	}
	out := new(DoltService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoltStorage) DeepCopyInto(out *DoltStorage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoltStorage.
func (in *DoltStorage) DeepCopy() *DoltStorage {
	if in == nil {
		return nil
	}
	out := new(DoltStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GasTown) DeepCopyInto(out *GasTown) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GasTown.
func (in *GasTown) DeepCopy() *GasTown {
	if in == nil {
		return nil
	}
	out := new(GasTown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GasTown) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GasTownDefaults) DeepCopyInto(out *GasTownDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GasTownDefaults.
func (in *GasTownDefaults) DeepCopy() *GasTownDefaults {
	if in == nil {
		return nil
	}
	out := new(GasTownDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GasTownList) DeepCopyInto(out *GasTownList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GasTown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GasTownList.
func (in *GasTownList) DeepCopy() *GasTownList {
	if in == nil {
		return nil
	}
	out := new(GasTownList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GasTownList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GasTownSpec) DeepCopyInto(out *GasTownSpec) {
	*out = *in
	out.DoltRef = in.DoltRef
	out.Defaults = in.Defaults
	in.Agents.DeepCopyInto(&out.Agents)
	if in.SecretsRef != nil {
		in, out := &in.SecretsRef, &out.SecretsRef
		*out = new(LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GasTownSpec.
func (in *GasTownSpec) DeepCopy() *GasTownSpec {
	if in == nil {
		return nil
	}
	out := new(GasTownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GasTownStatus) DeepCopyInto(out *GasTownStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileAt != nil {
		in, out := &in.LastReconcileAt, &out.LastReconcileAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GasTownStatus.
func (in *GasTownStatus) DeepCopy() *GasTownStatus {
	if in == nil {
		return nil
	}
	out := new(GasTownStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalRef) DeepCopyInto(out *LocalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalRef.
func (in *LocalRef) DeepCopy() *LocalRef {
	if in == nil {
		return nil
	}
	out := new(LocalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedRef) DeepCopyInto(out *NamespacedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedRef.
func (in *NamespacedRef) DeepCopy() *NamespacedRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rig) DeepCopyInto(out *Rig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rig.
func (in *Rig) DeepCopy() *Rig {
	if in == nil {
		return nil
	}
	out := new(Rig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RigAgents) DeepCopyInto(out *RigAgents) {
	*out = *in
	if in.MayorClaudeMdRef != nil {
		in, out := &in.MayorClaudeMdRef, &out.MayorClaudeMdRef
		*out = new(LocalRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RigAgents.
func (in *RigAgents) DeepCopy() *RigAgents {
	if in == nil {
		return nil
	}
	out := new(RigAgents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RigFormula) DeepCopyInto(out *RigFormula) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RigFormula.
func (in *RigFormula) DeepCopy() *RigFormula {
	if in == nil {
		return nil
	}
	out := new(RigFormula)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RigList) DeepCopyInto(out *RigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RigList.
func (in *RigList) DeepCopy() *RigList {
	if in == nil {
		return nil
	}
	out := new(RigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RigSpec) DeepCopyInto(out *RigSpec) {
	*out = *in
	in.Agents.DeepCopyInto(&out.Agents)
	if in.Formulas != nil {
		in, out := &in.Formulas, &out.Formulas
		*out = make([]RigFormula, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RigSpec.
func (in *RigSpec) DeepCopy() *RigSpec {
	if in == nil {
		return nil
	}
	out := new(RigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RigStatus) DeepCopyInto(out *RigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastConvergedAt != nil {
		in, out := &in.LastConvergedAt, &out.LastConvergedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RigStatus.
func (in *RigStatus) DeepCopy() *RigStatus {
	if in == nil {
		return nil
	}
	out := new(RigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TownAgents) DeepCopyInto(out *TownAgents) {
	*out = *in
	if in.SurveyorClaudeMdRef != nil {
		in, out := &in.SurveyorClaudeMdRef, &out.SurveyorClaudeMdRef
		*out = new(LocalRef)
		**out = **in
	}
	if in.SurveyorResources != nil {
		in, out := &in.SurveyorResources, &out.SurveyorResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TownAgents.
func (in *TownAgents) DeepCopy() *TownAgents {
	if in == nil {
		return nil
	}
	out := new(TownAgents)
	in.DeepCopyInto(out)
	return out
}
